#!/usr/bin/env bash
# Installs and configure HAproxy on the lb-01 server
# using roundrobin algorithm

sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy using roundrobin algorithm
sudo echo "
frontend driiis.tech-frontend
        bind *:80
        mode http
        default_backend driiis.tech-backend

backend driiis.tech-backend
        balance roundrobin
        server 124201-web-01 100.26.122.130:80 check
        server 124201-web-02 35.153.93.220:80 check
">> /etc/haproxy/haproxy.cfg

# Enable HAProxy management
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
