#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# configure nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Creating Sample Page
sudo echo "Hello World!" > /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

# configures an Nginx server so that /redirect_me is redirecting to another page
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default


# Restart Nginx
sudo service nginx restart
