#!/usr/bin/env bash
# Install nginx on my web01 server
# Configure nginx server so /redirect_me is redirecting to another page
# Redirection must be a 301 moved permanently
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "/server_name _;$/a \rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
