#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# code for error page 
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html

# configures an Nginx server so that /error_page 404 is redirecting to error page 
sudo sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
