#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "/server_name _;$/a \        }" /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _;$/a \                internal;" /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _;$/a \                root /usr/share/nginx/html;" /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _;$/a \        location = /custom_404.html {" /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _;$/a \        error_page 404 /custom_404.html;" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
