#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# code for http_response_header
sudo sed -i '11i\add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf

# Reload Nginx
sudo service nginx restart
