#!/usr/bin/env bash
# Installs and configure HAproxy on the lb-01 server
# using roundrobin algorithm

sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy using roundrobin algorithm
sudo echo "
frontend http_front
        bind *:80
        default_backend http_back

backend http_back
        balance roundrobin
        server 124201-web-01 54.227.196.53:80 check
        server 124201-web-02 35.153.98.2:80 check
">> /etc/haproxy/haproxy.cfg

# Enable HAProxy management
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy estart
