#!/usr/bin/env bash
# this script:
# Create file /var/run/myscript.pid
# containing its PID.
# Displays "To infinity and beyond" indefinitely.
# Displays "I hate the kill command" on SIGTERM signal.
# Displays "Y U no love me?!" on SIGINT signal.
# Deletes the pid file and terminates on SIGQUIT or SIGTERM signal.
file=/var/run/myscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; exit" SIGTERM
trap "rm $file; exit" SIGQUIT

echo $$ > "$file"

while true
do
    echo "To infinity and beyond"
    sleep 2
done
