#!/usr/bin/env bash
# this script displays "bad luck" if count is on 4, "good luck" if count is on 8, else displays "Best School"
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
	    echo "bad luck"
	elif [ $i -eq 8 ]
	then
	    echo "good luck"
       	else
	    echo "Best School"
	fi
	((count++))
done
