#!/usr/bin/env bash
# this script display the time for 12 hours and 59 minutes.
hour=0
minute=1
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    while [ $minute -lt 60 ]
    do
        echo "$minute"
        ((minute++))
    done
    ((hour++))
done
